# =============================================================================
# DOCKER COMPOSE FOR CHOUIEUR EXPRESS LOCAL DEVELOPMENT
# =============================================================================
# 
# This docker-compose file sets up the complete development environment
# including MongoDB, backend, and frontend services.
# 
# USAGE:
# ======
# Start all services: docker-compose up -d
# Stop all services:  docker-compose down
# View logs:          docker-compose logs -f
# 
# SERVICES:
# =========
# - mongodb: Local MongoDB instance for development
# - backend: Express API server
# - frontend: Next.js application
#

version: '3.8'

services:
  # =============================================================================
  # MONGODB DATABASE
  # =============================================================================
  mongodb:
    image: mongo:7.0
    container_name: chouieur-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: myapp_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - chouieur-network

  # =============================================================================
  # BACKEND API SERVER
  # =============================================================================
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chouieur-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/myapp_db?authSource=admin
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - chouieur-network

  # =============================================================================
  # FRONTEND APPLICATION
  # =============================================================================
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chouieur-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - chouieur-network

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  mongodb_data:
    driver: local

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  chouieur-network:
    driver: bridge